---
stages:
  - name: dev1
    inputs:
      - type: git
        branch: dev1
        service: ${SOURCE_CONTROL_SERVICE}
    triggers:
      - type: commit
    jobs:
      - name: distribution
        type: builder
        artifact_dir: archive
        enable_tests: true
        test_file_pattern: '*.xml, generated/*.xml'
        build_type: npm
        script: |-
          #!/bin/bash
          git config --global user.email "wgpannel@us.ibm.com"
          git config --global user.name "wil.pannell"

          export NVM_DIR=/home/pipeline/nvm
          export NODE_VERSION=v7.10.1
          export NVM_VERSION=v0.33.2
          npm config delete prefix \
            && curl https://raw.githubusercontent.com/creationix/nvm/${NVM_VERSION}/install.sh | sh \
            && . $NVM_DIR/nvm.sh \
            && nvm install $NODE_VERSION \
            && nvm alias default $NODE_VERSION \
            && nvm use default \
            && node -v \
            && npm -v \
            && export PATH=${NVM_DIR}/versions/node/${NODE_VERSION}/bin:./node_modules/.bin:$PATH

          git branch -a
          git branch integration
          git fetch origin integration
          git merge integration --ff-only

          npm install
          npm run ci
          npm run dist
          npm prune

          ls -al
          mkdir -p archive
          ls -al
          mkdir -p generated
          scripts/archive.sh
          git whatchanged --pretty=format:'%s %cn %h %cd' -1 > archive/changelog.txt

          git checkout integration
          git pull origin integration
          git merge dev1 --no-ff --log
          git push origin integration --no-verify

          git checkout --track origin/archive
          git merge dev1 --no-ff --log
          rm changelog.txt
          ls -al
          cp archive/changelog.txt .
          echo "${BUILD_NUMBER}" >> changelog.txt
          ls -al
          git add .
          git commit -m "$(cat archive/changelog.txt)" --no-verify
          git push origin archive --no-verify

          git checkout --track origin/distribution
          cp archive/* .
          git add .
          git commit -m "$(cat archive/changelog.txt)" --no-verify
          git push origin distribution --no-verify

          ls -al
  - name: integration
    inputs:
      - type: git
        branch: archive
        service: ${SOURCE_CONTROL_SERVICE}
    triggers:
      - type: commit
    properties:
    - name: SAUCE_USERNAME
      value: {{services.test.parameters.username}}
      type: text
    - name: SAUCE_ACCESS_KEY
      value: {{services.test.parameters.key}}
    jobs:
      - name: 'saucelabs'
        type: builder
        enable_tests: true
        test_file_pattern: '*.xml, generated/*.xml'
        build_type: npm
        script: |-
          #!/bin/bash
          git config --global user.email "wgpannel@us.ibm.com"
          git config --global user.name "wil.pannell"

          export NVM_DIR=/home/pipeline/nvm
          export NODE_VERSION=v7.10.1
          export NVM_VERSION=v0.33.2
          npm config delete prefix \
            && curl https://raw.githubusercontent.com/creationix/nvm/${NVM_VERSION}/install.sh | sh \
            && . $NVM_DIR/nvm.sh \
            && nvm install $NODE_VERSION \
            && nvm alias default $NODE_VERSION \
            && nvm use default \
            && node -v \
            && npm -v \
            && export PATH=${NVM_DIR}/versions/node/${NODE_VERSION}/bin:./node_modules/.bin:$PATH

          npm install
          mkdir -p generated
          npm run test:sauce
